services:
  postgres:
    image: postgres:12
    container_name: lsm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lsm-network

  springboot:
    container_name: lsm_springboot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - lsm-network

volumes:
  postgres_data:

networks:
  lsm-network:
    driver: bridge
