openapi: 3.0.0
info:
  title: LSM API Documentation
  description: API documentation for the Learning Management System (LSM) project.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  api/auth/register:
    post:
      summary: Register a new user
      description: Register a new user with a role.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestDTO'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad Request

  api/auth/login:
    post:
      summary: Login a user
      description: Authenticate a user and return a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDTO'
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

components:
  schemas:
    RegisterRequestDTO:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [STUDENT, TEACHER, ADMIN]
      required:
        - username
        - password
        - role

    LoginRequestDTO:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
